`treehouses led sandstorm` (fixes #2036)
treehouses/cli pull request #2039
Opened 2021-02-20 05:13 UTC by rjpadilla

Add `sandstorm`  sub-sub command `treehouses led`.

2021-02-24 23:37 UTC, JLKwong requested changes

2021-02-24 23:37 UTC, JLKwong commented on README.md
> +    [heavymetal|dance|kecak|sandstorm|random]
This line extends into the 'section' for the descriptions. Maybe you can move random to a new line?

2021-02-24 23:37 UTC, JLKwong commented on modules/help.sh
> +    [heavymetal|dance|kecak|sandstorm|random]
This line extends into the 'section' for the descriptions. Maybe you can move random to a new line?

2021-02-24 23:52 UTC, JLKwong approved these changes
This is very good, yes. 💯 ✨ 🎊

2021-02-25 01:13 UTC, dogi approved these changes

2021-02-25 01:17 UTC, merged