`treehouses shutdown` spelling fixed (fixes #2048)
treehouses/cli pull request #2052
Opened 2021-02-27 03:18 UTC by rjpadilla

2021-03-01 18:42 UTC, JLKwong requested changes

2021-03-01 18:42 UTC, JLKwong commented on modules/shutdown.sh
> +      echo "Shutting down in 60 seconds. Press ctrl+c to cancel"
Add a period at the end to read:
>      echo "Shutting down in 60 seconds. Press ctrl+c to cancel."

2021-03-01 18:42 UTC, JLKwong commented on modules/shutdown.sh
> +      echo "Shutting down in $2 seconds. Press ctrl+c to cancel"
Add a period at the end to read:
>      echo "Shutting down in $2 seconds. Press ctrl+c to cancel."

2021-03-01 18:42 UTC, JLKwong commented on modules/shutdown.sh
> +  echo "      System shutdown in 60 seconds. Press ctrl+c to cancel"
Add a period at the end to read:
> "      System shutdown in 60 seconds. Press ctrl+c to cancel."

2021-03-01 18:42 UTC, JLKwong commented on modules/shutdown.sh
> +  echo "      System will shutdown after the specified time. Press ctrl+c to cancel"
Add a period at the end to read:
> "      System will shutdown after the specified time. Press ctrl+c to cancel."

2021-03-01 19:05 UTC, JLKwong requested changes
On Line 22:
>        echo "Error: only now, in and force options are supported"

This should be revised to clarify that the options are options:
>        echo "Error: only the options 'now', 'in', and 'force' are supported"

2021-03-04 02:44 UTC, JLKwong approved these changes
Control is better than Corntol. 🌽

2021-03-04 04:05 UTC, dogi approved these changes

2021-03-04 04:08 UTC, merged