`treehouses message` fix style (fixes #2049)
treehouses/cli pull request #2053
Opened 2021-02-27 04:23 UTC by rjpadilla

2021-03-04 02:28 UTC, dogi commented on modules/message.sh
> +                           <show|read|mark> <group>]"
@rjpadilla better to use in each line an own `echo`

2021-03-06 00:04 UTC, JLKwong requested changes
This line is wrapping off-screen for me when I do split screen in bash.
>   echo "  $BASENAME message gitter send treehouses/Lobby \"Hi, you are very awesome\""

2021-03-08 17:19 UTC, rjpadilla commented
> 
> 
> This line is wrapping off-screen for me when I do split screen in bash.
> 
> > echo "  $BASENAME message gitter send treehouses/Lobby "Hi, you are very awesome""

So I tested this in git bash and it works fine. Maybe its a font size or monitor issue?

2021-03-12 23:51 UTC, JLKwong approved these changes
My font size is too big. D:

2021-03-15 18:46 UTC, dogi approved these changes

2021-03-15 18:56 UTC, merged